name: GITHUB_ENV
on: push
jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      - name: source
        run: echo "RESULT=hello-w" >> "${GITHUB_ENV}"
      - name: target
        run: echo "${RESULT}"
